services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: museion-app
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        container_name: museion-webserver
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - app-network

    db:
        image: mysql:8.0
        container_name: museion-db
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    db-data:
